COURSE_ACTS(COURSE_BOB, _(" 2 ZOMB-OMB HILLS"), 	_("KING ZOMB-OMB ON THE ISLAND"), 	_("MOUNTAIN ESCAPING"), 	_("FIND THE REAL BOX"), 	_("RED COINS OF THE HILLS"), 	_("STARLING OF THE TREES"), 	_("ON TOP OF THE FENCE"))

COURSE_ACTS(COURSE_WF, _(" 1 AIR FORT"), 	_("DESTROY THE BOOKCASE"), 	_("CLIMB THE BIG TOWER"), 	_("GATHER THE RED COINS"), 	_("COLLECT 5 SECRET COINS"), 	_("UNDER THE TOWER"), 	_("REMEMBER THE WALL..."))

COURSE_ACTS(COURSE_JRB, _("10 EVERSHADE LAGOON"), 	_("LOOT THE SUNKEN SHIP"), 	_("EERIE THE EEL"), 	_("BOX SWITCH RUN"), 	_("THE CAVE'S RED COINS"), 	_("THE PHANTOM PIRATE SHIP"), 	_("HIDDEN STARLING OF THE LAGOON"))

COURSE_ACTS(COURSE_CCM, _(" 5 LOST GLACIER"), 	_("TOP O' THE GLACIER"), 	_("FIND THE LOST PENGUIN"), 	_("RIDE IN THE SLIDE"), 	_("RED COINS IN THE BLIZZARD"), 	_("SHREDDING THE GLACIER"), 	_("SECRET OF THE SLIDE"))

COURSE_ACTS(COURSE_BBH, _(" ? BOO MOON HOTEL"), 	_("BIG BOO'S BASEMENT COMBAT"), 	_("IN THE BASEMENT"), 	_("RACE THROUGH THE BACKDOOR"), 	_("RED COIN HIDE'N'SEEK"), 	_("MAGIC BOX MYSTERIA"), 	_("THE LIBRARY'S SECRET"))

COURSE_ACTS(COURSE_HMC, _(" 3 ICE CAVERN"), 	_("DOWN BELOW THE CAVERN"), 	_("ICY RED COIN PUZZLE"), 	_("THE SWITCH IS GONE?"), 	_("A-MAZE-ING SECRET HUNT"), 	_("WALL KICKS ALWAYS WORK"), 	_("BEHIND THE GATE"))

COURSE_ACTS(COURSE_LLL, _(" 6 HOT, HOT PLAINS"), 	_("MAKE THE BULLY SWEAT"), 	_("RED HOT-HEADED COINS"), 	_("STEADY SINKIN' STONES"), 	_("PUZZLES IN THE SKY"), 	_("VOLCANIC ACTION NO.1"), 	_("VOLCANIC ACTION NO.2"))

COURSE_ACTS(COURSE_SSL, _(" 9 DUSTY CATA'TOMB"), 	_("CHASE THE CONDOR"), 	_("STAND ON THE PILLARS"), 	_("INSIDE THE ANCIENT TOMB"), 	_("GUARDIAN OF THE TOMB"), 	_("DESERTING 8 RED COINS"), 	_("THOSE YELLOW COINS AGAIN"))

COURSE_ACTS(COURSE_DDD, _(" 8 ABANDONED HARBOR"), 	_("SWIM IN A HURRY"), 	_("RINGS OF THE MANTA RAY"), 	_("POLE PERFORMANCE"), 	_("RED COINS ON SHORE"), 	_("BE TWEESTED!"), 	_("PEARL TREASURE HUNT"))

COURSE_ACTS(COURSE_SL, _(" ? "), 	_(""), 	_(""), 	_(""), 	_(""), 	_(""), 	_(""))

COURSE_ACTS(COURSE_WDW, _(" 7 WATERY DEPTHS"), 	_("READY FOR BLAST OFF!"), 	_("EXPANDING ARROW LIFTS"), 	_("THOSE YELLOW COINS"), 	_("SOMEWHERE IN THE DEPTHS"), 	_("THE TOWN'S RED COINS"), 	_("STRANDED IN THE TOWN"))

COURSE_ACTS(COURSE_TTM, _("12 FLOWERSIDE PATCH"), 	_("SUPER SLIDE MADNESS"), 	_("SECRET OF THE MUSHROOMS"), 	_("FLOWERING 8 RED COINS"), 	_("SKYWARD SPOTLIGHTS"), 	_("UNDERWATER SWITCH"), 	_("THE FLOWER UNDERSIDE"))

COURSE_ACTS(COURSE_THI, _("11 PIRANHA FOREST"), 	_("BUG OFF, WIGGLER!"), 	_("BEWARE OF PIRANHA FISHES"), 	_("5 TINY-HUGE SECRETS"), 	_("SURF UPON THE HILLSIDE"), 	_("HUGE RED COIN ADVENTURE"), 	_("LONELY ISLAND IN THE SKY"))

COURSE_ACTS(COURSE_TTC, _("13 CLOCKWORK FACTORY"), 	_("CRASH INTO THE GUARDED CAGE"), 	_("ACROSS THE MOVING BARS"), 	_("BOXES OF MAGIC"), 	_("TOP O' THE CLOCK"), 	_("RIGHT UNDER YOUR FEET"), 	_("RED COINS OF THE CLOCK"))

COURSE_ACTS(COURSE_RR, _(" 4 NIGHT SKY HEIGHTS"), 	_("SCALE THE BIG MAZE"), 	_("AHOY, SHIP ABOARD!"), 	_("RED COINS OF THE MANSION"), 	_("THROUGH THE RINGS"), 	_("SWINGING UNDER THE MAZE"), 	_("PICK A BOX"))

SECRET_STAR(15, _("   KING BOO'S MOON COMPLEX"))
SECRET_STAR(16, _("   KING BOO'S BOILER RUINS"))
SECRET_STAR(17, _("   KING BOO'S DIMENSION VOID"))
SECRET_STAR(18, _("   KING BOO'S SECRET SLIDE"))
SECRET_STAR(19, _("   IRON CAP OF THE IGLOO"))
SECRET_STAR(20, _("   NIGHT OF THE WING CAP"))
SECRET_STAR(21, _("   UNDERGROUND BASEMENT"))
SECRET_STAR(22, _("   MOONLIGHT HEAVEN"))
SECRET_STAR(23, _("   HAUNTED POOL CUBE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   SECRET STARLINGS"))
EXTRA_TEXT(0,_("YOU'VE FOUND A SECRET STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
